### ISSUE TITLE
Issue with cuda

### ISSUE THREAD

**Issue by ThanhPham1987** [ben-omji/serve_yolov5#1]
Hi
When I run command line: sudo ./setup.sh box. I face this issue:

docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
Failed, Please check stdout above

Would you like to help me to solve?

Best regards,
PeterPham

**Comment by ben-omji** [comment]
Hi, @ThanhPham1987 

In `setup.sh`, Line 23
``` bash
docker run -it --rm -u root --gpus all ...
```
You can see the `--gpu` option which need the "NVIDIA Container Toolkit".

I forgot to add the "NVIDIA Container Toolkit" on the built with section in README.
You can refer these pages. ([nvidia-docker](https://github.com/NVIDIA/nvidia-docker), [contrainer-toolkit installation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#install-guide))

Actually, I guess it could be run without `--gpu` option but it's not tested.
Please check what you can do and reply for update.

Thanks.

**Comment by ben-omji** [comment]
It looks like you are on the next step. (#2)
So I'm closing this but feel free to reopen.
