### ISSUE TITLE
ModuleNotFoundError: No module named 'ts.torch_handler.handler_box'

### ISSUE THREAD

**Issue by ThanhPham1987** [ben-omji/serve_yolov5#3]
Hi @ben-omji 
How to solve this issue?
ModuleNotFoundError: No module named 'ts.torch_handler.handler_box'
Best regards,
PeterPham

**Comment by ben-omji** [comment]
@ThanhPham1987 
Could you give me more information about your issue? 
And please show me if you have any changes to the code.

**Comment by ThanhPham1987** [comment]
Hi @ben-omji . When I run this command line:./run_ts.sh coco_yolov5s.mar. And I access container. I see the log inside container. I see this bug "ModuleNotFoundError: No module named 'ts.torch_handler.handler_box' "
Best regards,
PeterPham

**Comment by ben-omji** [comment]
@ThanhPham1987 
Updating torch serve repository version from 0.7.1 -> 0.8.1 solve that issue.
Check the [line 17 of setup.sh](https://github.com/ben-omji/serve_yolov5/blob/main/setup.sh#L17)
